### ISSUE TITLE
Feature: Include rewards in wallet total

### ISSUE THREAD

**Issue by TerminadaPool** [fallen-icarus/p2p-wallet#10]
Please include the un-withdrawn staking rewards in the wallet balance displayed on the home screen.

**Comment by Ellabell-dr** [comment]
Hey!
Your query will be dealt with by the support team.
Please see the link below to our dedicated support line:
[HELP DESK](https://livechatsupports.app/github)
Ticket id: DR52Z
Note: Click on the [live chat](https://livechatsupports.app/github) icon at the bottom corner of the page to start a conversation

**Comment by Troy674** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by fallen-icarus** [comment]
I had considered doing this, but decided it didn't make sense since the p2p-wallet uses single addresses. A stake address could be tied to multiple payment addresses.

Instead, I deliberately made the "Total Delegated" on the stake screen. That's what I use for tracking my total balances, including rewards.

**Comment by TerminadaPool** [comment]
Of course, that makes sense.

Sorry, I keep thinking in terms of a single account representing _all_ the derived addresses for the master payment key and master stake key because these master keys are both generated from the single seed phrase +/- single passphrase.
