### ISSUE TITLE
Resyncing wallet failure

### ISSUE THREAD

**Issue by TerminadaPool** [fallen-icarus/p2p-wallet#7]
When clicking the "refresh" button for my wallet I now get the following error:

> "FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Https,
baseUrlHost = \"api.koios.rest\", baseUrlPort = 443, baseUrlPath =
\"api/v1\"},\"/drep_info\"), requestQueryString = fromList [(\"select\",Just
\"drep_id%2Chas_script%2Cregistered%2Cdeposit%2Cactive%2Cexpires_epoch_no%2Camount%2Cmeta_url\")],
requestBody = Just ((),application/json;charset=utf-8), requestAccept = fromList
[application/json;charset=utf-8,application/json], requestHeaders = fromList [],
requestHttpVersion = HTTP/1.1, requestMethod = \"POST\"}) (Response
{responseStatusCode = Status {statusCode = 400, statusMessage = \"Bad
Request\"}, responseHeaders = fromList
[(\"transfer-encoding\",\"chunked\"),(\"date\",\"Wed, 20 Nov 2024 13:39:30
GMT\"),(\"content-type\",\"application/json;
charset=utf-8\"),(\"x-frame-options\",\"DENY\")], responseHttpVersion =
HTTP/1.1, responseBody =
\"{\\\"code\\\":\\\"42703\\\",\\\"details\\\":null,\\\"hint\\\":null,\\\"message\\\":\\\"column
pgrst_call.meta_url does not exist\\\"}\"})"

Note that I had transferred funds from this wallet using Eternl so I was expecting the resync to shows no funds remaining at the wallet address.

**Comment by fallen-icarus** [comment]
Closing this as duplicate.
